### ISSUE TITLE
Analyze provided data

### ISSUE THREAD

**Issue by siddhant-28** [seng499-company2/algorithm2#1]
As an algorithm 2 developer, it would be useful to fully understand the provided historical data. 

Data provided: enrollment data(announcement in slack), historical enrollment data(json)(stored in company2 slack channel)

**Acceptance Criteria:**
- [ ] Developer can easily explain the following about provided data:
- [ ] All content (eg columns and rows)
- [ ] The format (eg table format with rows and cols)
- [ ] The context of the data (how it relates to the problem of alg2)
- [ ] List of at least 2 algorithmic approaches, how those approaches work, and pros and cons between them.

**Tasks:**

- Create visualizations of data trends for historical data (class size)(waitlist size)(# of people in year)
- Analyze visualizations and make a summary 
- Provide recommendation for alg 2 accuracy requirement
