### ISSUE TITLE
Heuristics Based Module

### ISSUE THREAD

**Issue by siddhant-28** [seng499-company2/algorithm2#11]
**Acceptance Criteria**

- Capacity assigned for each input course (no error messages!)

**Tasks**

- [x]  Define the heuristic to use
- [ ]  Define cases for each module use case and implement approach for each case
- [x] Format the output in schedule object
