### ISSUE TITLE
Sanity Checking and Final Formatting

### ISSUE THREAD

**Issue by siddhant-28** [seng499-company2/algorithm2#12]
**Acceptance Criteria**

- Outputs schedule object with the capacities within the defined bounds.
- Compare against the original schedule object to check if everything is in order.
- Schedule object complies with the output data models.

**Tasks**

- [x] Combine courses from the heuristics and Auto-ARIMA module
- [ ] Perform sanity checks on size, course order and course number
- [ ] Perform scaling if capacity out of bounds
- [ ] Compare output to original schedule object
- [ ]  Fix all errors that come up
- [ ] Conform the output the data models
- [ ] Return output to main module
