### ISSUE TITLE
Integrating Modules

### ISSUE THREAD

**Issue by siddhant-28** [seng499-company2/algorithm2#20]
**Acceptance Criteria**

- No run-time errors when running tests
- Modules conform to the flow diagram and uses inputs from previous modules
- Integration test-suite
- Mock data for testing

**Tasks**

- [x] Write a script to construct mock data objects - mock schedule data, mock historical data, mock enrollment
- [x] Construct extensive integrations tests
- [x] Check module inputs/outputs
