### ISSUE TITLE
Overall Testing

### ISSUE THREAD

**Issue by siddhant-28** [seng499-company2/algorithm2#21]
**Acceptance Criteria**

- Identify bottlenecks/performance constraints globally and per module
- Edge cases fixed (if any)
- Performance/Stability ironed out

**Tasks**

- [ ] Identify edge cases and fix them
- [ ] Identify bottlenecks and fix them
- [ ] Report on application performance (CPU/RAM/Runtime) (ticket comment)
- [ ] Report on overall application stability (ticket comment)

**Comment by siddhant-28** [comment]
Doc: https://docs.google.com/document/d/1BbPYqZFaDrPg-Q8FxXYzu5zKei6bCHmpHBCNkC-UhKs/edit?usp=sharing
