### ISSUE TITLE
Evaluate Estimates

### ISSUE THREAD

**Issue by siddhant-28** [seng499-company2/algorithm2#22]
**Acceptance Criteria**

- Report on any anomalies in the capacities
- Report on effects of COVID on capacities
- Schedule object only goes through one module (ARIMA/Heuristics)
- Generate script to compare forecasted capacities vs actual capacities for every historical year

**Tasks**

- [x] Identify any anomalies in the capacities
- [x] Evaluate effects of COVID on capacities
- [x] Make necessary changes to make schedule object go through only one module
