### ISSUE TITLE
Improve forecasting for courses with no data

### ISSUE THREAD

**Issue by siddhant-28** [seng499-company2/algorithm2#36]
**Acceptance Criteria**

- [x] Courses with no data have capacities assigned
- [x] Make sure all courses have a capacity
- [x] Make sure all the integration test pass

**Tasks**

- Implement the "Average" heuristic
- Implement the fallback option (hardcoded values)
- Testing
