### ISSUE TITLE
Format JSON According to Data Models

### ISSUE THREAD

**Issue by siddhant-28** [seng499-company2/algorithm2#9]
**Acceptance Criteria**

- Two JSON files constructed - Historical Capacities and Program Enrolment
- Agreement with company 1 
- Common repository for the files

**Tasks**

- [x] Trim & Construct historical capacities json according to data models
- [x] Construct program enrolment json according to data models
- [x] Coordinate with company 1 regarding alignment
- [x]  Store the file in a common repository

**Comment by JonahKoebernick** [comment]
Data was merged into main, just need to communicate with company 1 about the existence of the data, and agreement on the data, then we can close this issue.
